<?php

namespace Smartshore\SignUpBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ListsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListsRepository extends EntityRepository
{
}
