Smartshore\SignUpBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: Smartshore\SignUpBundle\Entity\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        firstName:
            type: string
            length: 255
        lastName:
            type: string
            length: 255
        email:
            type: string
            length: 255
            column: Email
        password:
            type: string
            length: 255
            column: Password
        UserName:
            type: string
            length: 255
        status:
            type: smallint
            column: Status
    lifecycleCallbacks: {  }
