lists:
    path:     /
    defaults: { _controller: "SmartshoreSignUpBundle:Lists:index" }

lists_show:
    path:     /{id}/show
    defaults: { _controller: "SmartshoreSignUpBundle:Lists:show" }

lists_new:
    path:     /new
    defaults: { _controller: "SmartshoreSignUpBundle:Lists:new" }

lists_create:
    path:     /create
    defaults: { _controller: "SmartshoreSignUpBundle:Lists:create" }
    requirements: { _method: post }

lists_edit:
    path:     /{id}/edit
    defaults: { _controller: "SmartshoreSignUpBundle:Lists:edit" }

lists_update:
    path:     /{id}/update
    defaults: { _controller: "SmartshoreSignUpBundle:Lists:update" }
    requirements: { _method: post|put }

lists_delete:
    path:     /{id}/delete
    defaults: { _controller: "SmartshoreSignUpBundle:Lists:delete" }
    requirements: { _method: post|delete }
lists_deleteList:
    path:     /{id}/delete
    defaults: { _controller: "SmartshoreSignUpBundle:Lists:deleteList" }